kafka:
  topics:
    - rcp-request
  bootstrap:
    servers: ${KAFKA_SERVER_URI:localhost:9092}
  consumer:
    auto-commit:
      enabled: false
      interval-ms: 100
    session-timeout-ms: 15000
    group-id: mygroup
    auto-offset-reset: earliest
client:
  buffer-size: 100

server:
  port: ${KAFKA_WEB_CLIENT_PORT:8080}